version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests=true

  pre_build:
    commands:
      - echo Building artifact...
      - mvn package -DskipTests=true

  build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - target/StockPricesApp-0.0.1-SNAPSHOT.jar